version: '3.0'

services:
  main:
    container_name: main
    build: ./server
    environment:
      - RDS_HOST=postgres
    env_file:
      - ./server/.env
    ports:
      - 3001:3001
    depends_on:
      - postgres
  client:
    build: ./client
    container_name: client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - ./server/.env
    environment:
      - PG_DATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: